// Generated by https://quicktype.io

export interface Comment {
  id:          number;
  content:     string;
  downvotes:   number;
  created_at:  string;
  reply_to_id: number | null;
  updated_at:  string;
  upvotes:     number;
  user_id:     number;
  user:        User;
  replies?:    Comment[];
}

export interface User {
  id:         number;
  name:       string;
  username:   string;
  updated_at: string;
  last_seen:  null;
  created_at: string;
}
