// Generated by https://quicktype.io

export interface Comment {
  content: string;
  created_at: string;
  downvotes: number;
  id: number;
  updated_at: string;
  upvotes: number;
  user: User;
  reply_to: ReplyTo | null;
}

export interface User {
  id: number;
  last_seen: string;
  name: string;
  username: string;
}

export interface ReplyTo {
  id: number;
  user_id: number;
}
