# name: nextjs-cloud-run

# on:
#   push:
#     branches:
#       - main

# env:
#   CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
#   CLOUD_RUN_REGION: us-central1
#   REPO_NAME: interactive-comments

# jobs:
#   build-and-deploy:
#     name: build and deploy
#     runs-on: ubuntu-latest
#     - name: checkout
#       uses: actions/checkout@v3

#     - name: setup gcloud
#       uses: google-github-actions/auth@v0
#       with:
#         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

#     - name: Enable the necessary APIs and enable docker auth
#       run: |-
#         gcloud services enable containerregistry.googleapis.com
#         gcloud services enable run.googleapis.com
#         gcloud --quiet auth configure-docker
#     - name: Build and tag image
#       run: |-
#         docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
#     - name: Push image to GCR
#       run: |-
#         docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
#     - name: Deploy
#       run: |-
#         gcloud components install beta --quiet
#         gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
#           --project $CLOUD_RUN_PROJECT_ID \
#           --platform managed \
#           --region $CLOUD_RUN_REGION \
#           --allow-unauthenticated \
#           --quiet
